### ISSUE TITLE
Cleanup ENABLE_FORGIVING_JWT_COOKIES toggle and related code

### ISSUE THREAD

**Issue by feanil** [openedx/edx-drf-extensions#365] opened 2023-07-26 15:42 UTC
Once https://github.com/openedx/edx-drf-extensions/pull/197 has landed and we've managed to migrate to forgiving JWT Auth, we'll want to update the code here so that forgiving JWT auth is the default and the other code is removed.

* Cleanup the ENABLE_FORGIVING_JWT_COOKIES 
* Cleanup code that uses it so that we retain the code that would run if `ENABLE_FORGIVING_JWT_COOKIES=True`

**Comment by robrap** [comment] 2023-08-10 21:23
- We may want a DEPR ticket?
- Clean-up includes removing `USE_JWT_COOKIE` (and `USE-JWT-COOKIE`) as well.
  - [Github search in openedx org](https://github.com/search?q=org%3Aopenedx+%28USE_JWT_COOKIE+OR++USE-JWT-COOKIE%29&type=code).
  -  [Github search in edx org](https://github.com/search?q=org%3Aedx+%28USE_JWT_COOKIE+OR++USE-JWT-COOKIE%29&type=code).

**Comment by robrap** [comment] 2024-08-28 19:09
This ticket is now a duplicate of the DEPR, so I am closing this ticket.
- https://github.com/openedx/edx-drf-extensions/issues/371

**Closed by robrap** 2024-08-28 19:09 UTC
